//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.CARRITOes = new HashSet<CARRITO>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int ID_USUARIO { get; set; }
        public int Precio { get; set; }
        public int ID_Categoria { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
        public string Ubicacion { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public byte[] imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRITO> CARRITOes { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual ESTADO ESTADO1 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
