//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporte_usuario
    {
        public int ID { get; set; }
        public int ID_usuario_reporte { get; set; }
        public int ID_usuario_reportado { get; set; }
        public int ID_publicacion { get; set; }
        public string descripcion { get; set; }
    }
}
